In [1]:
import pandas as pd
import random
import numpy as np
import pandas as pd
from faker import Faker

In [2]:
df = pd.read_csv('pharmacity_personal_care.csv').drop(columns=['URL'])

df

,ProductID,ProductName,Category,CategoryCode,SourceSlug,Brand,Price,OriginalPrice,DiscountPercent,Unit,Rating,TotalSold
0,P07609,Lăn Khử Mùi NIVEA Ngọc Trai Quyến Rũ (chai 25ml),Lăn khử mùi,lan-khu-mui,san-pham-khu-mui,Nivea,49500,49500,0.0,Chai,4.75,7423
1,P00326,Bột Khử Mùi TRAPHA Hỗ Trợ Khử Mùi (chai 30g),Sáp khử mùi,sap-khu-mui,san-pham-khu-mui,Trapha,18000,18000,0.0,Hộp,4.66,19906
2,P26024,Sáp Khử Mùi NIVEA Ngọc Trai Quyến Rũ (Chai 50ml),Sáp khử mùi,sap-khu-mui,san-pham-khu-mui,Nivea,68250,105000,35.0,Chai,4.60,7040
3,P03828,Xịt Ngăn Mùi NIVEA Extra Whitening Trắng Mịn M...,Xịt khử mùi,xit-khu-mui,san-pham-khu-mui,Nivea,116000,116000,0.0,Chai,4.87,5487
4,P17958,Lăn Khử Mùi ETIAXIL Dành Cho Da Nhạy Cảm (chai...,Lăn khử mùi,lan-khu-mui,san-pham-khu-mui,Etiaxil,270100,370000,27.0,Chai,4.69,7060
...,...,...,...,...,...,...,...,...,...,...,...,...
440,P37331,Kem tẩy lông da nhạy cảm Cleo (50g),Hỗ trợ tẩy lông,san-pham-ho-tro-tay-long,cham-soc-co-the,Cleo,75650,89000,15.0,Tuýp,4.77,1143
441,P11334,Kem tẩy lông cho da thường Cléo (25g),Hỗ trợ tẩy lông,san-pham-ho-tro-tay-long,cham-soc-co-the,Cleo,28800,48000,40.0,Tuýp,4.60,6651
442,P07056,Sữa Dưỡng Thể VASELINE HEALTHY BRIGHT Sáng Da ...,Dưỡng thể & massage,dau-duong-the-massage,cham-soc-co-the,Vaseline,88200,98000,10.0,Chai,4.56,6445
443,P01562,Sữa Dưỡng Da Toàn Thân VASELINE HEALTHY BRIGHT...,Dưỡng thể & massage,dau-duong-the-massage,cham-soc-co-the,Vaseline,88200,98000,10.0,Chai,4.97,5533
444,P11331,Kem tẩy lông cho da nhạy cảm Cléo Hair Removal...,Hỗ trợ tẩy lông,san-pham-ho-tro-tay-long,cham-soc-co-the,Cleo,28800,48000,40.0,Tuýp,4.82,7010

In [3]:
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
fake = Faker("vi_VN")
Faker.seed(SEED)
n=1000

df = pd.read_csv("pharmacity_personal_care.csv").drop(columns=["URL"])

products = df.sample(n=n,replace=True,random_state=42).reset_index(drop=True)

customer_ids = [f"C{i:04d}"for i in range(1, n + 1)]

customer_names = [fake.name()for _ in range(n)]

ages = np.random.normal(loc=30,scale=10,size=n).round().astype(int)

ages = np.clip(ages, 18, 70)

genders = random.choices(['Nam', 'Nữ'],weights=[0.45, 0.55],k=n)

cities = random.choices(['TP. Hồ Chí Minh','Hà Nội','Đà Nẵng','Cần Thơ','Hải Phòng'], weights=[0.40, 0.30, 0.10, 0.10, 0.10],k=n)
payment_methods = random.choices(['Tiền mặt','Thẻ ngân hàng','Ví điện tử','COD'],weights=[0.20, 0.25, 0.25, 0.30],k=n)

quantities = np.random.choice([1, 2, 3, 4, 5],size=n,p=[0.50, 0.25, 0.15, 0.07, 0.03])

purchase_dates = pd.to_datetime(np.random.choice(pd.date_range('2026-01-01','2026-09-30'),size=n))

total_amount = (products['Price'].values * quantities)

Order_df = pd.DataFrame({'OrderID': [f'ORD{i:05d}'for i in range(1, n + 1)],
'CustomerID': customer_ids,
'CustomerName': customer_names,
'Age': ages,
'Gender': genders,
'ProductID': products['ProductID'].values,
'ProductName': products['ProductName'].values,
'Category': products['Category'].values,
'Brand': products['Brand'].values,
'Price': products['Price'].values,
'Quantity': quantities,
'TotalAmount': total_amount,
'PurchaseDate': purchase_dates,
'City': cities,
'PaymentMethod': payment_methods})

In [4]:
print("Kích thước dataset:", Order_df.shape)

display(Order_df.head(5))

Kích thước dataset: (1000, 15)

,OrderID,CustomerID,CustomerName,Age,Gender,ProductID,ProductName,Category,Brand,Price,Quantity,TotalAmount,PurchaseDate,City,PaymentMethod
0,ORD00001,C0001,An Vũ,35,Nữ,P18999,Dầu Gội TRESEMME Salon Rebond Giúp Giảm Gãy Rụ...,Dầu gội đầu,Tresemme,194400,1,194400,2026-07-09,TP. Hồ Chí Minh,Tiền mặt
1,ORD00002,C0002,Chị Lan Trần,29,Nam,P13420,Sáp dưỡng ẩm Vaseline Pure Petroleum Jelly Ori...,Dưỡng thể & massage,Vaseline,61000,1,61000,2026-05-16,Hà Nội,Ví điện tử
2,ORD00003,C0003,Khoa Bùi,36,Nam,P12848,Tã quần mỏng thoáng size L cho người lớn Caryn...,Tã dán,Caryn,189660,2,379320,2026-02-12,Hà Nội,Thẻ ngân hàng
3,ORD00004,C0004,Ngọc Trần,45,Nam,P30966,Kotex BVS Mặt Bông Cotton SMC 24cm 8M,Băng vệ sinh,Kotex,40000,2,80000,2026-03-31,Hải Phòng,Thẻ ngân hàng
4,ORD00005,C0005,Chị Vân Hoàng,28,Nữ,P21174,Serum Dưỡng Tóc ELLIPS Giúp Tóc Phục Hồi Hư Tổ...,Dưỡng tóc,Ellips,203000,1,203000,2026-09-02,TP. Hồ Chí Minh,Tiền mặt

In [5]:
Order_df.to_csv('pharmacity_simulated_transactions.csv',index=False,encoding='utf-8-sig')

print("Đã xuất file:")
print("pharmacity_simulated_transactions.csv")

Đã xuất file:
pharmacity_simulated_transactions.csv